# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20160417_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infofield',
            name='profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='description',
            new_name='long_description',
        ),
        migrations.AddField(
            model_name='profile',
            name='header_photo',
            field=models.ImageField(blank=True, upload_to='header_photos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default=2, upload_to='profile_photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='short_description',
            field=models.CharField(default='short description', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='InfoField',
        ),
    ]
