# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20160425_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='source_file',
            field=models.FileField(blank=True, upload_to='promise_source_files'),
        ),
        migrations.AddField(
            model_name='promise',
            name='source_link',
            field=models.URLField(blank=True),
        ),
    ]
