# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
        ('profiles', '0005_auto_20160505_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country'),
            preserve_default=False,
        ),
    ]
